"""Financial Statement Intelligence — full taxonomy, 18 categories, 195 signals.
Every signal is a spec dict the scoring engine consumes. status: 'live' = compute
function exists; 'defined' = mapped, compute pending (returns None, never faked).
"""
from __future__ import annotations

def _s(id, label, field, weight, good, great, hib=True, status="defined",
       floor=None, floor_score=30.0, cap=None, cap_score=85.0,
       peer_key=None, evidence=""):
    d = {"id": id, "label": label, "field": field, "weight": weight,
         "higher_is_better": hib, "good": good, "great": great,
         "status": status, "evidence": evidence}
    if floor is not None: d["floor"] = floor; d["floor_score"] = floor_score
    if cap is not None:   d["cap"] = cap; d["cap_score"] = cap_score
    if peer_key:          d["peer_key"] = peer_key
    return d

CATEGORIES = {
 "revenue": ("Revenue Intelligence", 10, [
   _s("total_revenue_growth","Total revenue growth","rev_growth_yoy",4,0.05,0.20,status="live",floor=-0.05,floor_score=25,peer_key="rev_growth_yoy",evidence="latest FY revenue vs prior FY, 10-K"),
   _s("rev_cagr_3y","Revenue 3y CAGR","rev_cagr_3y",3,0.05,0.15,status="live",peer_key="rev_cagr_3y",evidence="3-year revenue CAGR"),
   _s("rev_cagr_5y","Revenue 5y CAGR","rev_cagr_5y",3,0.05,0.15,status="live",evidence="5-year revenue CAGR"),
   _s("qoq_growth","QoQ revenue growth","rev_growth_qoq",2,0.0,0.08,status="live",evidence="latest quarter vs prior"),
   _s("organic_revenue_growth","Organic revenue growth","organic_rev_growth",3,0.03,0.15,evidence="growth ex-acquisitions"),
   _s("inorganic_revenue_growth","Acquisition-driven growth","inorganic_rev_growth",1,0.0,0.10,hib=False,evidence="growth from M&A"),
   _s("revenue_by_segment","Segment revenue detail","segment_count",1,2,5,evidence="reported segments"),
   _s("segment_concentration","Segment concentration","segment_hhi",2,0.5,0.2,hib=False,evidence="HHI across segments"),
   _s("geographic_revenue_mix","Geographic diversification","geo_diversification",2,0.3,0.7,evidence="revenue by geography"),
   _s("customer_concentration","Customer concentration","customer_concentration",3,0.3,0.1,hib=False,evidence="top customer share"),
   _s("customer_retention","Customer retention","customer_retention",2,0.85,0.95,evidence="retention rate"),
   _s("new_customer_growth","New customer growth","new_customer_growth",1,0.05,0.20,evidence="customer count growth"),
   _s("recurring_revenue_pct","Recurring revenue %","recurring_rev_pct",3,0.3,0.7,evidence="recurring share"),
   _s("subscription_revenue_pct","Subscription revenue %","subscription_pct",2,0.2,0.6,evidence="subscription share"),
   _s("contract_revenue","Contracted revenue","contract_rev_pct",1,0.2,0.6,evidence="under-contract share"),
   _s("revenue_visibility","Revenue visibility","revenue_visibility",2,0.4,0.8,evidence="forward visibility"),
   _s("backlog","Backlog coverage","backlog_ratio",2,0.5,1.5,evidence="backlog / revenue"),
   _s("book_to_bill","Book-to-bill ratio","book_to_bill",2,1.0,1.2,evidence="orders / billings"),
   _s("pricing_power","Pricing power","pricing_power",3,0.0,0.05,evidence="price contribution"),
   _s("price_vs_volume_growth","Price vs volume","price_volume_ratio",2,0.3,0.6,evidence="price/volume split"),
   _s("revenue_quality","Revenue quality","revenue_quality",3,0.6,0.9,evidence="cash-backed composite"),
   _s("revenue_predictability","Revenue predictability","rev_growth_persistence",2,0.0,0.02,status="live",evidence="growth trend slope"),
   _s("revenue_seasonality","Seasonality control","revenue_seasonality",1,0.3,0.1,hib=False,evidence="seasonal variance"),
   _s("fx_impact","FX exposure","fx_impact",1,0.1,0.02,hib=False,evidence="currency impact"),
   _s("one_time_revenue","One-time revenue reliance","one_time_rev_pct",2,0.05,0.0,hib=False,evidence="non-recurring items"),
   _s("guidance_accuracy","Guidance accuracy","guidance_accuracy",2,0.7,0.95,evidence="guidance vs actual"),
   _s("historical_miss_rate","Revenue miss rate","rev_miss_rate",2,0.3,0.1,hib=False,evidence="consensus miss freq"),
   _s("revenue_beat_frequency","Revenue beat frequency","rev_beat_freq",2,0.5,0.8,evidence="consensus beat freq"),
   _s("tam_penetration","TAM penetration","tam_penetration",1,0.1,0.4,evidence="revenue vs TAM"),
   _s("market_share_growth","Market share growth","market_share_growth",2,0.0,0.03,evidence="vs industry growth"),
   _s("revenue_sustainability","Revenue sustainability","revenue_sustainability",2,0.5,0.85,evidence="durability composite"),
   _s("revenue_volatility","Revenue volatility","rev_volatility",2,0.2,0.05,hib=False,status="live",evidence="stdev of growth"),
   _s("revenue_cyclicality","Revenue cyclicality","rev_cyclicality",2,0.6,0.2,hib=False,evidence="cycle correlation"),
   _s("revenue_diversification","Revenue diversification","rev_diversification",2,0.3,0.7,evidence="spread composite"),
   _s("acquisition_dependency","Acquisition dependency","acquisition_dependency",2,0.4,0.1,hib=False,evidence="M&A reliance"),
   _s("churn","Customer churn","churn",2,0.15,0.05,hib=False,evidence="churn rate"),
   _s("cross_sell_growth","Cross-sell growth","cross_sell_growth",1,0.0,0.05,evidence="cross-sell"),
   _s("upsell_growth","Upsell / expansion","upsell_growth",1,0.0,0.10,evidence="net expansion"),
   _s("revenue_per_customer","Revenue per customer","rev_per_customer",1,0.0,0.05,evidence="rev/customer trend"),
   _s("revenue_per_employee","Revenue per employee","rev_per_employee",2,300000,600000,status="live",evidence="rev/employee"),
   _s("revenue_efficiency","Revenue efficiency","revenue_efficiency",1,0.5,0.8,evidence="rev per capital"),
   _s("deferred_revenue_growth","Deferred revenue growth","deferred_rev_growth",2,0.0,0.15,evidence="deferred rev"),
   _s("pipeline_quality","Pipeline quality","pipeline_quality",1,0.4,0.8,evidence="pipeline strength"),
   _s("sales_conversion_rate","Sales conversion","sales_conversion",1,0.2,0.4,evidence="close rate"),
   _s("sales_productivity","Sales productivity","sales_productivity",1,0.5,0.9,evidence="rev per S&M dollar"),
   _s("distribution_expansion","Distribution expansion","distribution_expansion",1,0.0,0.10,evidence="channel growth"),
   _s("international_expansion","International expansion","intl_expansion",1,0.0,0.15,evidence="intl rev growth"),
   _s("product_mix_shift","Product mix shift","product_mix_shift",1,0.0,0.05,evidence="toward higher margin"),
   _s("long_term_revenue_outlook","Long-term revenue outlook","lt_revenue_outlook",2,0.4,0.8,evidence="forward durability"),
 ]),
 "income_statement": ("Income Statement Intelligence", 12, [
   _s("operating_leverage","Operating leverage","operating_leverage",3,1.0,1.5,status="live",evidence="%dEBIT / %dRev"),
   _s("expense_ratio_trend","Expense ratio trend","expense_ratio_trend",2,0.0,-0.02,hib=False,evidence="opex/rev trend"),
   _s("sga_efficiency","SG&A efficiency","sga_to_revenue",2,0.25,0.12,hib=False,status="live",evidence="SG&A/rev"),
   _s("rd_intensity","R&D intensity","rd_to_revenue",2,0.05,0.15,status="live",evidence="R&D/rev"),
   _s("depreciation_trend","Depreciation trend","depreciation_trend",1,0.0,0.0,hib=False,evidence="D&A/rev"),
   _s("interest_expense_trend","Interest expense burden","interest_to_revenue",2,0.05,0.01,hib=False,status="live",evidence="interest/rev"),
   _s("tax_rate_trend","Effective tax rate","effective_tax_rate",1,0.30,0.15,hib=False,status="live",evidence="eff tax rate"),
   _s("nonrecurring_items","Non-recurring items","nonrecurring_pct",2,0.05,0.0,hib=False,evidence="one-time items"),
   _s("operating_expense_growth","Opex vs revenue growth","opex_vs_rev_growth",2,0.0,-0.05,hib=False,status="live",evidence="opex-rev growth"),
   _s("cost_inflation_exposure","Cost inflation exposure","cost_inflation_exposure",1,0.5,0.2,hib=False,evidence="cost sensitivity"),
   _s("incremental_margins","Incremental margins","incremental_margin",3,0.2,0.4,status="live",evidence="dEBIT/dRev"),
   _s("expense_discipline","Expense discipline","expense_discipline",2,0.5,0.85,evidence="cost control"),
   _s("fixed_vs_variable_cost","Cost structure flexibility","fixed_cost_ratio",1,0.7,0.4,hib=False,evidence="fixed/variable"),
   _s("breakeven_analysis","Breakeven margin","breakeven_margin",1,0.8,0.6,hib=False,evidence="breakeven rev"),
   _s("cost_per_unit_trend","Unit cost trend","cost_per_unit_trend",1,0.0,-0.02,hib=False,evidence="unit cost"),
   _s("overhead_ratio","Overhead ratio","overhead_ratio",1,0.2,0.1,hib=False,evidence="overhead/rev"),
   _s("expense_seasonality","Expense seasonality","expense_seasonality",1,0.3,0.1,hib=False,evidence="seasonal exp"),
   _s("one_time_charges","One-time charges","one_time_charge_freq",2,0.4,0.1,hib=False,evidence="special charges"),
   _s("restructuring_frequency","Restructuring frequency","restructuring_freq",1,0.4,0.1,hib=False,evidence="restructuring"),
   _s("impairment_history","Impairment history","impairment_freq",2,0.3,0.0,hib=False,evidence="impairments"),
 ]),
 "gross_profit": ("Gross Profit Intelligence", 6, [
   _s("gross_margin","Gross margin","gross_margin",4,0.30,0.60,status="live",peer_key="gross_margin",evidence="GP/rev TTM"),
   _s("gross_margin_trend","Gross margin trend","gross_margin_trend",3,0.0,0.02,status="live",evidence="GM direction"),
   _s("gross_margin_stability","Gross margin stability","gross_margin_stability",3,0.6,0.95,status="live",evidence="moat proxy"),
   _s("gross_margin_vs_peers","Gross margin vs peers","gross_margin",2,0.30,0.60,status="live",peer_key="gross_margin",evidence="sector percentile"),
   _s("cogs_efficiency","COGS efficiency","cogs_efficiency",2,0.7,0.4,hib=False,status="live",evidence="COGS/rev"),
   _s("input_cost_management","Input cost management","input_cost_mgmt",2,0.5,0.85,evidence="margin hold"),
   _s("gross_profit_growth","Gross profit growth","gross_profit_growth",3,0.05,0.20,status="live",evidence="GP growth"),
   _s("margin_expansion_capacity","Margin expansion capacity","margin_expansion_capacity",2,0.0,0.05,evidence="headroom"),
   _s("pricing_vs_cost_spread","Price-cost spread","price_cost_spread",2,0.0,0.03,evidence="price-cost"),
   _s("gross_margin_cyclicality","Gross margin cyclicality","gross_margin_cyclicality",1,0.5,0.2,hib=False,evidence="cycle sensitivity"),
 ]),
 "operating_profit": ("Operating Profit Intelligence", 6, [
   _s("operating_margin","Operating margin","operating_margin",4,0.10,0.25,status="live",peer_key="operating_margin",evidence="OI/rev"),
   _s("operating_margin_trend","Operating margin trend","operating_margin_trend",3,0.0,0.02,status="live",evidence="OM direction"),
   _s("operating_margin_stability","Operating margin stability","operating_margin_stability",3,0.6,0.95,status="live",evidence="OM stability"),
   _s("ebit_growth","EBIT growth","ebit_growth",3,0.05,0.20,status="live",evidence="OI growth"),
   _s("operating_leverage_realized","Realized operating leverage","operating_leverage",2,1.0,1.5,status="live",evidence="EBIT vs rev"),
   _s("operating_margin_vs_peers","Operating margin vs peers","operating_margin",2,0.10,0.25,status="live",peer_key="operating_margin",evidence="sector percentile"),
   _s("operating_efficiency_trend","Operating efficiency trend","operating_efficiency_trend",2,0.0,0.02,evidence="opex eff"),
   _s("margin_durability","Margin durability","margin_durability",2,0.5,0.85,evidence="downturn hold"),
   _s("operating_scalability","Operating scalability","operating_scalability",2,0.5,0.85,evidence="scale margin"),
 ]),
 "ebitda": ("EBITDA Intelligence", 5, [
   _s("ebitda_margin","EBITDA margin","ebitda_margin",4,0.15,0.35,status="live",evidence="EBITDA/rev"),
   _s("ebitda_growth","EBITDA growth","ebitda_growth",3,0.05,0.20,status="live",evidence="EBITDA growth"),
   _s("ebitda_stability","EBITDA stability","ebitda_stability",2,0.6,0.9,status="live",evidence="EBITDA stability"),
   _s("ebitda_to_fcf_conversion","EBITDA to FCF conversion","ebitda_fcf_conversion",3,0.5,0.8,evidence="FCF/EBITDA"),
   _s("adjusted_ebitda_quality","Adjusted EBITDA quality","adj_ebitda_quality",2,0.7,0.95,hib=False,evidence="adj gap"),
   _s("ebitda_vs_peers","EBITDA margin vs peers","ebitda_margin",2,0.15,0.35,status="live",peer_key="ebitda_margin",evidence="sector percentile"),
   _s("ebitda_margin_trend","EBITDA margin trend","ebitda_margin_trend",2,0.0,0.02,status="live",evidence="EBITDA direction"),
 ]),
 "net_income": ("Net Income Intelligence", 6, [
   _s("net_margin","Net margin","net_margin",4,0.05,0.20,status="live",evidence="NI/rev"),
   _s("net_income_growth","Net income growth","net_income_growth",3,0.05,0.20,status="live",evidence="NI growth"),
   _s("net_margin_stability","Net margin stability","net_margin_stability",3,0.6,0.95,status="live",evidence="NM stability"),
   _s("earnings_quality_ratio","Earnings quality","earnings_quality_ratio",3,0.8,1.1,status="live",evidence="OCF/NI"),
   _s("nonoperating_income_reliance","Non-operating income reliance","nonop_income_pct",2,0.2,0.05,hib=False,evidence="non-op share"),
   _s("net_margin_vs_peers","Net margin vs peers","net_margin",2,0.05,0.20,status="live",peer_key="net_margin",evidence="sector percentile"),
   _s("bottom_line_predictability","Net income predictability","net_income_predictability",2,0.5,0.85,evidence="NI consistency"),
   _s("earnings_persistence","Earnings persistence","earnings_persistence",2,0.5,0.85,evidence="autocorrelation"),
 ]),
 "eps": ("EPS Intelligence", 5, [
   _s("eps_growth","EPS growth","eps_growth",4,0.05,0.20,status="live",evidence="diluted EPS growth"),
   _s("eps_cagr_3y","EPS 3y CAGR","eps_cagr_3y",3,0.05,0.15,status="live",evidence="3y EPS CAGR"),
   _s("eps_cagr_5y","EPS 5y CAGR","eps_cagr_5y",3,0.05,0.15,evidence="5y EPS CAGR"),
   _s("eps_stability","EPS stability","eps_stability",2,0.6,0.9,status="live",evidence="EPS stability"),
   _s("diluted_vs_basic_gap","Dilution gap","dilution_gap",2,0.05,0.01,hib=False,evidence="dilution"),
   _s("share_count_trend","Share count trend","share_count_trend",3,0.0,-0.02,hib=False,evidence="buybacks reduce"),
   _s("eps_beat_frequency","EPS beat frequency","eps_beat_freq",2,0.5,0.8,evidence="EPS beat freq"),
   _s("eps_revision_trend","EPS revision trend","eps_revision_trend",2,0.0,0.02,evidence="revision direction"),
 ]),
 "balance_sheet": ("Balance Sheet Intelligence", 12, [
   _s("asset_growth","Asset growth","asset_growth",2,0.03,0.15,status="live",evidence="asset growth"),
   _s("asset_quality","Asset quality","asset_quality",3,0.5,0.85,evidence="tangible share"),
   _s("goodwill_ratio","Goodwill ratio","goodwill_ratio",2,0.4,0.1,hib=False,status="live",evidence="goodwill/assets"),
   _s("intangibles_ratio","Intangibles ratio","intangibles_ratio",1,0.5,0.2,hib=False,evidence="intangibles/assets"),
   _s("tangible_book_value","Tangible book value","tangible_book_ratio",2,0.3,0.7,evidence="tangible equity"),
   _s("asset_turnover","Asset turnover","asset_turnover",3,0.5,1.5,status="live",evidence="rev/assets"),
   _s("asset_efficiency","Asset efficiency","asset_efficiency",2,0.5,0.85,evidence="output/assets"),
   _s("off_balance_sheet_risk","Off-balance-sheet risk","off_bs_risk",2,0.3,0.05,hib=False,evidence="leases/SPEs"),
   _s("inventory_quality","Inventory quality","inventory_quality",2,0.5,0.85,evidence="freshness"),
   _s("receivables_quality","Receivables quality","receivables_quality",2,0.5,0.85,evidence="collectibility"),
   _s("asset_writedown_history","Writedown history","writedown_freq",1,0.3,0.0,hib=False,evidence="writedowns"),
   _s("balance_sheet_strength","Balance sheet strength","balance_sheet_strength",3,0.5,0.9,status="live",evidence="composite"),
 ]),
 "cash_flow": ("Cash Flow Intelligence", 12, [
   _s("ocf_growth","Operating cash flow growth","ocf_growth",3,0.05,0.20,status="live",evidence="OCF growth"),
   _s("fcf_growth","FCF growth","fcf_growth",3,0.05,0.20,status="live",evidence="FCF growth"),
   _s("fcf_margin","FCF margin","fcf_margin",4,0.05,0.20,status="live",evidence="FCF/rev"),
   _s("fcf_conversion","FCF conversion","fcf_conversion",4,0.8,1.1,status="live",evidence="FCF/NI"),
   _s("cash_conversion_cycle","Cash conversion cycle","cash_conversion_cycle",2,60,20,hib=False,evidence="DSO+DIO-DPO"),
   _s("capex_intensity","Capex intensity","capex_intensity",2,0.10,0.03,hib=False,status="live",evidence="capex/rev"),
   _s("maintenance_vs_growth_capex","Maintenance vs growth capex","maint_capex_ratio",2,0.7,0.4,hib=False,evidence="maint share"),
   _s("fcf_stability","FCF stability","fcf_stability",3,0.6,0.9,status="live",evidence="FCF stability"),
   _s("cash_flow_quality","Cash flow quality","cash_flow_quality",3,0.7,0.95,evidence="OCF backing"),
   _s("ocf_to_net_income","OCF / net income","ocf_to_net_income",3,0.9,1.2,status="live",evidence="OCF/NI"),
   _s("fcf_yield","FCF yield","fcf_yield",2,0.03,0.08,evidence="FCF/mktcap"),
   _s("cash_generation_consistency","Cash generation consistency","cash_gen_consistency",2,0.6,0.9,status="live",evidence="positive FCF years"),
 ]),
 "working_capital": ("Working Capital Intelligence", 5, [
   _s("days_sales_outstanding","Days sales outstanding","dso",2,60,30,hib=False,evidence="receivables days"),
   _s("days_inventory","Days inventory","dio",2,90,40,hib=False,evidence="inventory days"),
   _s("days_payable","Days payable","dpo",1,30,60,evidence="payables days"),
   _s("cash_conversion_cycle_wc","Cash conversion cycle","cash_conversion_cycle",3,60,20,hib=False,evidence="CCC"),
   _s("working_capital_efficiency","Working capital efficiency","wc_efficiency",2,0.5,0.85,evidence="rev/WC"),
   _s("working_capital_trend","Working capital trend","wc_trend",1,0.0,-0.02,hib=False,evidence="WC/rev trend"),
   _s("net_working_capital_ratio","Net working capital ratio","nwc_ratio",1,0.1,0.05,hib=False,evidence="NWC/rev"),
 ]),
 "capital_allocation": ("Capital Allocation Intelligence", 6, [
   _s("reinvestment_rate","Reinvestment rate","reinvestment_rate",3,0.3,0.6,evidence="reinvested/earnings"),
   _s("incremental_roic","Incremental ROIC","incremental_roic",4,0.10,0.25,evidence="dNOPAT/dIC"),
   _s("buyback_yield","Buyback yield","buyback_yield",2,0.0,0.04,status="live",evidence="net buybacks/mktcap"),
   _s("buyback_timing_quality","Buyback timing quality","buyback_timing",2,0.4,0.8,evidence="below intrinsic"),
   _s("dividend_growth","Dividend growth","dividend_growth",2,0.0,0.08,evidence="DPS growth"),
   _s("dividend_coverage","Dividend coverage","dividend_coverage",2,1.5,3.0,evidence="FCF/dividends"),
   _s("ma_track_record","M&A track record","ma_track_record",3,0.4,0.8,evidence="value created"),
   _s("goodwill_impairment_rate","Goodwill impairment rate","goodwill_impairment_rate",2,0.2,0.0,hib=False,status="live",evidence="M&A quality tell"),
   _s("capital_allocation_discipline","Capital allocation discipline","capital_alloc_discipline",3,0.5,0.85,evidence="composite"),
   _s("shareholder_yield","Shareholder yield","shareholder_yield",2,0.02,0.06,status="live",evidence="div+buybacks/mktcap"),
 ]),
 "profitability": ("Profitability Intelligence", 6, [
   _s("roic","ROIC","roic",4,0.08,0.20,status="live",peer_key="roic",evidence="NOPAT/invested capital"),
   _s("roic_wacc_spread","ROIC - WACC spread","roic_wacc_spread",5,0.0,0.15,status="live",floor=0.0,floor_score=30,peer_key="roic",evidence="value-creation test"),
   _s("roe","Return on equity","roe",3,0.10,0.25,status="live",peer_key="roe",evidence="NI/equity"),
   _s("roa","Return on assets","roa",2,0.03,0.10,status="live",peer_key="roa",evidence="NI/assets"),
   _s("roce","Return on capital employed","roce",3,0.10,0.20,evidence="EBIT/cap employed"),
   _s("roic_trend","ROIC trend","roic_trend",3,0.0,0.01,status="live",evidence="ROIC direction"),
   _s("roic_stability","ROIC stability","roic_stability",3,0.6,0.9,status="live",evidence="moat durability"),
   _s("cash_roic","Cash ROIC","cash_roic",2,0.08,0.20,evidence="FCF/invested capital"),
   _s("dupont_decomposition","DuPont quality","dupont_quality",2,0.5,0.85,evidence="margin x turnover x lev"),
   _s("profitability_vs_peers","Profitability vs peers","roic",2,0.08,0.20,status="live",peer_key="roic",evidence="ROIC percentile"),
 ]),
 "efficiency": ("Efficiency Intelligence", 4, [
   _s("asset_turnover_eff","Asset turnover","asset_turnover",3,0.5,1.5,status="live",evidence="rev/assets"),
   _s("inventory_turnover","Inventory turnover","inventory_turnover",2,4,10,evidence="COGS/inventory"),
   _s("receivables_turnover","Receivables turnover","receivables_turnover",2,6,12,evidence="rev/receivables"),
   _s("revenue_per_employee_eff","Revenue per employee","rev_per_employee",2,300000,600000,status="live",evidence="rev/employees"),
   _s("sga_to_revenue","SG&A efficiency","sga_to_revenue",2,0.25,0.12,hib=False,status="live",evidence="SG&A/rev"),
   _s("capital_efficiency","Capital efficiency","capital_efficiency",3,0.5,0.85,evidence="output/capital"),
 ]),
 "liquidity": ("Liquidity Intelligence", 4, [
   _s("current_ratio","Current ratio","current_ratio",3,1.2,2.0,status="live",evidence="CA/CL"),
   _s("quick_ratio","Quick ratio","quick_ratio",3,1.0,1.5,status="live",evidence="(CA-inv)/CL"),
   _s("cash_ratio","Cash ratio","cash_ratio",2,0.3,0.8,status="live",evidence="cash/CL"),
   _s("operating_cash_ratio","Operating cash ratio","operating_cash_ratio",2,0.4,1.0,status="live",evidence="OCF/CL"),
   _s("defensive_interval","Defensive interval","defensive_interval",1,90,270,evidence="days covered"),
 ]),
 "solvency": ("Solvency Intelligence", 4, [
   _s("debt_to_equity","Debt to equity","debt_to_equity",3,1.0,0.3,hib=False,status="live",evidence="debt/equity"),
   _s("debt_to_ebitda","Debt to EBITDA","debt_to_ebitda",3,3.0,1.0,hib=False,status="live",evidence="debt/EBITDA"),
   _s("interest_coverage","Interest coverage","interest_coverage",3,4.0,10.0,evidence="EBIT/interest"),
   _s("net_debt_to_ebitda","Net debt to EBITDA","net_debt_to_ebitda",2,2.5,0.5,hib=False,status="live",evidence="(debt-cash)/EBITDA"),
   _s("debt_maturity_profile","Debt maturity profile","debt_maturity_risk",1,0.4,0.1,hib=False,evidence="near-term maturities"),
   _s("altman_z","Altman Z-score","altman_z",2,1.8,3.0,evidence="bankruptcy composite"),
 ]),
 "accounting_quality": ("Accounting Quality Intelligence", 4, [
   _s("accruals_ratio","Accruals ratio","accruals_ratio",3,0.05,-0.05,hib=False,status="live",evidence="(NI-OCF)/assets"),
   _s("sloan_ratio","Sloan ratio","sloan_ratio",2,0.10,0.0,hib=False,status="live",evidence="accruals/assets"),
   _s("beneish_m_score","Beneish M-score","beneish_m",3,-2.22,-3.0,hib=False,evidence="manipulation prob"),
   _s("cash_earnings_gap","Cash-earnings gap","cash_earnings_gap",2,0.2,0.05,hib=False,status="live",evidence="earnings-cash gap"),
   _s("revenue_recognition_flags","Revenue recognition flags","rev_rec_flags",2,0.3,0.0,hib=False,evidence="aggressive rev-rec"),
   _s("days_sales_manipulation","DSRI","dsri",1,1.1,1.0,hib=False,evidence="receivables index"),
 ]),
 "financial_trend": ("Financial Trend Intelligence", 3, [
   _s("multi_year_trend_consistency","Multi-year consistency","trend_consistency",3,0.5,0.85,status="live",evidence="improvement consistency"),
   _s("acceleration_deceleration","Acceleration","growth_acceleration",2,0.0,0.02,status="live",evidence="2nd derivative"),
   _s("inflection_detection","Inflection detection","inflection_signal",2,0.0,0.5,evidence="turning point"),
   _s("trend_durability","Trend durability","trend_durability",2,0.5,0.85,evidence="trend persistence"),
 ]),
 "financial_risk": ("Financial Risk Intelligence", 4, [
   _s("leverage_risk","Leverage risk","leverage_risk",3,0.5,0.1,hib=False,status="live",evidence="leverage stress"),
   _s("liquidity_risk","Liquidity risk","liquidity_risk",3,0.5,0.1,hib=False,status="live",evidence="funding stress"),
   _s("refinancing_risk","Refinancing risk","refinancing_risk",2,0.5,0.1,hib=False,evidence="maturity wall"),
   _s("covenant_headroom","Covenant headroom","covenant_headroom",2,0.2,0.5,evidence="covenant cushion"),
   _s("earnings_volatility_risk","Earnings volatility","earnings_volatility",2,0.3,0.1,hib=False,status="live",evidence="earnings stdev"),
   _s("bankruptcy_probability","Bankruptcy probability","bankruptcy_prob",3,0.2,0.02,hib=False,status="live",evidence="default probability"),
 ]),
}

FINANCIAL_STATEMENT = {"label": "Financial Statement Intelligence", "weight": 1.0, "categories": CATEGORIES}
